export const RECEIPT_EXAMPLES = [
  "HERTA JAMB S/C -25% SEL\nDANONE YOG FRAISE\nPAIN CAMPAGNE\nCOCA COLA 1.5L\nBEURRE DOUX 250G",
  "LAIT ENT. BIO 1L\nOEUFS X12 PLEIN AIR\nSAUCISSON PUR PORC JB\nSOIGNON ST MAURE 200G\nLOT: JB-776",
  "HARIBO TAGADA\nCEREALES LION\nBISCUITS CHOCO\nSIROP GLUCOSE TEST\nYAOURT NATURE X4"
];
